### ISSUE TITLE
Proposal Review

### ISSUE THREAD

**Issue by Chris210634** [AdiBhan/LaneWise#1]
Nice proposal.

The main feedback I have is with regards to the clustering. I'm not sure what data you would be clustering. If I understand you correctly, you plan on using OpenCV to detect the vehicles and calculate the speed of vehicles in each lane. If you're doing this in real time, then you can just recommend the fastest lane.

Edit: I see now you are going to cluster data with two features: speed and frequency. This sounds good.

Make sure to figure out early how you plan on scraping the webcam data.

**Comment by AdiBhan** [comment]
Thanks, I actually don't know if I can get live data (was a bit ambitious in the proposal) as they aren't any public way to get live feed. I've narrowed down the proposal to just images.
